import {DataFetcher} from '/lib/enonic/react4xp';
//import {helloProcessor} from './components/hello/HelloProcessor';
import {commonProcessor} from '/react4xp/components/common/CommonProcessor';
import {articleProcessor} from "./components/content/ArticleProcessor";
import {personProcessor} from './components/content/PersonProcessor';
import {playlistProcessor} from './components/content/PlaylistProcessor';
import {childListProcessor} from './components/parts/ChildListProcessor';
import {headingProcessor} from './components/parts/HeadingProcessor';
import {movieProcessor} from "./components/parts/MovieProcessor";
import {factboxProcessor} from "./components/macro/FactboxProcessor";

export const dataFetcher = new DataFetcher();
//dataFetcher.addContentType('portal:site', { processor: helloProcessor });
dataFetcher.addCommon({processor: commonProcessor});
dataFetcher.addPart('tutorial.nxp:heading', {processor: headingProcessor});
dataFetcher.addContentType('tutorial.nxp:person', {processor: personProcessor});
dataFetcher.addPart('tutorial.nxp:movie-details', {processor: movieProcessor});
dataFetcher.addPart('tutorial.nxp:child-list', {processor: childListProcessor});
dataFetcher.addContentType('tutorial.nxp:playlist', {processor: playlistProcessor});
dataFetcher.addContentType('tutorial.nxp:article', {processor: articleProcessor});
dataFetcher.addMacro('factbox', {processor: factboxProcessor});
